# Generated by Django 5.1.2 on 2024-10-24 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ref_app.referralcode'),
        ),
    ]
