# Generated by Django 5.1.2 on 2024-10-24 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0003_alter_user_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcode',
            name='user_id',
        ),
        migrations.AddField(
            model_name='referralcode',
            name='user',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ref_app.referralcode'),
        ),
    ]
