# Generated by Django 5.1.2 on 2024-10-24 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0004_remove_referralcode_user_id_referralcode_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ref_app.referralcode', to_field='code'),
        ),
    ]
