# Generated by Django 5.1.2 on 2024-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0006_alter_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
