# Generated by Django 5.1.2 on 2024-10-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0007_referralcode_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
